language: ruby
dist: xenial
cache: bundler

addons:
  apt:
    packages:
    - wrk
    - apache2-utils
  homebrew:
    packages:
    - wrk

script: bundle exec rspec

matrix:
  include:
    - rvm: 2.5
    - rvm: 2.6
    - rvm: 2.7
    - rvm: 2.6
      env: COVERAGE=PartialSummary,Coveralls
    - rvm: truffleruby
    - rvm: jruby-head
      env: JRUBY_OPTS="--debug -X+O"
    - rvm: ruby-head
    - rvm: 2.7
      os: osx
  allow_failures:
    - rvm: truffleruby
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: truffleruby

# after_success:
#   - bundle exec rake h2spec:all
